Ooprefactor
EPFL-BIO-210/demo-project pull request #5
Opened 2021-12-05 19:11 UTC by AlexEMG

Refactored code in oop style as suggested in pset 11. 

Tested the Euler method. For small enough dt, I get the same results (dashed is for `integrate.odeint`)
![rabbits_and_foxes100000](https://user-images.githubusercontent.com/20850270/144760112-9e613307-6708-4eba-a0e6-7f8885b780eb.png)

For too large, it doesn't work (as expected)

![rabbits_and_foxes100](https://user-images.githubusercontent.com/20850270/144760151-8e40125d-9eff-4d3c-a034-8a756169a013.png)

2021-12-07 12:29 UTC, LucZot commented on LotkaVolterraClass.py
> +# Comparing the two methods (overlaid)
Good test for checking if previous implementation and oop implementation work in the same way!
Maybe it would be cleaner to outsource the comparison in another (test) function or script instead of having it here with the class definitions?

2021-12-07 14:40 UTC, vargas95 requested changes
Thanks @AlexEMG . The oop refactor and the test comparison look great. I agree with @LucZot , it would be great to have a module for the classes and a different script for the test comparison.

2021-12-08 17:20 UTC, AlexEMG commented
Made test script.

2021-12-08 17:25 UTC, vargas95 approved these changes
Thanks for the edits!

2021-12-08 17:57 UTC, LucZot approved these changes

2021-12-08 19:52 UTC, merged